2021-07-05 18:17:52,190 : getLog.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 63, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-05 18:23:00,435 : getLog.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 63, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-06 09:08:21,328 : getLog.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 64, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-06 17:09:26,649 : operateMysql.py : ERROR : sahqingkuang
2021-07-06 17:59:31,895 : getLog.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 65, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-07 16:16:19,706 : getLog.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 64, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-12 09:39:58,448 : getVerificationCode.py : INFO : 已定位验证码
2021-07-12 09:39:58,465 : getVerificationCode.py : INFO : 获取验证码各顶点坐标
2021-07-12 09:39:58,546 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 09:39:59,198 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 09:42:04,966 : getVerificationCode.py : INFO : 已定位验证码
2021-07-12 09:42:04,982 : getVerificationCode.py : INFO : 获取验证码各顶点坐标
2021-07-12 09:42:05,060 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 09:42:05,247 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 09:45:19,543 : getLog.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 71, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-12 09:45:19,543 : getLog.py : ERROR : can't multiply sequence by non-int of type 'str'
2021-07-12 09:45:41,609 : getLog.py : ERROR : can't multiply sequence by non-int of type 'str'
2021-07-12 09:46:19,067 : getLog.py : ERROR : can't multiply sequence by non-int of type 'str'
2021-07-12 09:47:15,672 : getLog.py : ERROR : can't multiply sequence by non-int of type 'str'
2021-07-12 10:06:35,832 : getLog.py : ERROR : can't multiply sequence by non-int of type 'str'
2021-07-12 10:09:52,779 : getLog.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 82, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-12 10:11:21,300 : getLog.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 82, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-12 10:11:41,750 : getLog.py : DEBUG : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 82, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-12 10:12:10,771 : getLog.py : INFO : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 82, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-12 10:12:44,150 : getLog.py : WARNING : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 82, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-12 10:14:38,514 : getLog.py : INFO : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 82, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-12 10:18:05,293 : getLog.py : INFO : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 82, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-12 10:18:35,506 : getLog.py : INFO : traceback.format_exc()
2021-07-12 10:22:02,539 : getVerificationCode.py : INFO : hahahahhaha
2021-07-12 10:22:02,539 : getVerificationCode.py : INFO : hahahahhaha
2021-07-12 10:22:03,169 : getVerificationCode.py : INFO : hahahahhaha
2021-07-12 10:22:03,169 : getVerificationCode.py : INFO : hahahahhaha
2021-07-12 10:22:03,169 : getVerificationCode.py : INFO : hahahahhaha
2021-07-12 10:22:03,169 : getVerificationCode.py : INFO : hahahahhaha
2021-07-12 10:23:02,771 : getVerificationCode.py : INFO : hahahahhaha
2021-07-12 10:23:02,771 : getVerificationCode.py : INFO : hahahahhaha
2021-07-12 10:23:02,771 : getVerificationCode.py : INFO : waawwaaw
2021-07-12 10:23:02,771 : getVerificationCode.py : INFO : waawwaaw
2021-07-12 10:23:03,431 : getVerificationCode.py : INFO : hahahahhaha
2021-07-12 10:23:03,431 : getVerificationCode.py : INFO : hahahahhaha
2021-07-12 10:23:03,431 : getVerificationCode.py : INFO : hahahahhaha
2021-07-12 10:23:03,431 : getVerificationCode.py : INFO : hahahahhaha
2021-07-12 10:23:03,431 : getVerificationCode.py : INFO : waawwaaw
2021-07-12 10:23:03,431 : getVerificationCode.py : INFO : waawwaaw
2021-07-12 10:23:03,431 : getVerificationCode.py : INFO : waawwaaw
2021-07-12 10:23:03,431 : getVerificationCode.py : INFO : waawwaaw
2021-07-12 10:25:57,378 : getVerificationCode.py : INFO : 已定位验证码
2021-07-12 10:25:57,393 : getVerificationCode.py : INFO : 获取验证码各顶点坐标
2021-07-12 10:25:57,393 : getVerificationCode.py : INFO : 获取验证码各顶点坐标
2021-07-12 10:25:57,472 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 10:25:57,472 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 10:25:57,472 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 10:25:57,711 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:25:57,711 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:25:57,711 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:25:57,711 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:27:35,430 : getLog.py : INFO : traceback.format_exc()
2021-07-12 10:27:35,430 : getLog.py : INFO : weishahuiliangci
2021-07-12 10:28:02,319 : getLog.py : INFO : zhejiuhenqiguai
2021-07-12 10:28:02,319 : getLog.py : INFO : zhejiuhenqiguai
2021-07-12 10:28:02,320 : getLog.py : INFO : traceback.format_exc()
2021-07-12 10:28:02,320 : getLog.py : INFO : weishahuiliangci
2021-07-12 10:28:31,258 : getLog.py : INFO : zhejiuhenqiguai
2021-07-12 10:28:31,258 : getLog.py : INFO : zhejiuhenqiguai
2021-07-12 10:29:33,292 : getLog.py : INFO : zhejiuhenqiguai
2021-07-12 10:29:41,106 : getLog.py : INFO : zhejiuhenqiguai
2021-07-12 10:30:04,460 : getLog.py : INFO : zhejiuhenqiguai
2021-07-12 10:30:22,744 : getLog.py : INFO : zhejiuhenqiguai
2021-07-12 10:31:56,842 : getLog.py : INFO : zhejiuhenqiguai
2021-07-12 10:32:03,212 : getLog.py : INFO : zhejiuhenqiguai
2021-07-12 10:32:47,284 : getVerificationCode.py : INFO : 已定位验证码
2021-07-12 10:33:22,918 : getVerificationCode.py : INFO : 获取验证码各顶点坐标
2021-07-12 10:33:22,918 : getVerificationCode.py : INFO : 获取验证码各顶点坐标
2021-07-12 10:35:48,574 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 10:35:48,574 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 10:35:48,574 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 10:35:49,943 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:35:49,943 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:35:49,943 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:35:49,943 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:36:26,377 : getVerificationCode.py : INFO : 已定位验证码
2021-07-12 10:36:26,392 : getVerificationCode.py : INFO : 获取验证码各顶点坐标
2021-07-12 10:36:26,392 : getVerificationCode.py : INFO : 获取验证码各顶点坐标
2021-07-12 10:36:26,473 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 10:36:26,473 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 10:36:26,473 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 10:36:26,691 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:36:26,691 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:36:26,691 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:36:26,691 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:37:25,467 : getVerificationCode.py : INFO : 已定位验证码
2021-07-12 10:37:45,936 : getVerificationCode.py : INFO : 获取验证码各顶点坐标
2021-07-12 10:37:45,936 : getVerificationCode.py : INFO : 获取验证码各顶点坐标
2021-07-12 10:38:23,207 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 10:38:23,207 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 10:38:23,207 : getVerificationCode.py : INFO : 已二值化处理图片
2021-07-12 10:38:30,560 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:38:30,560 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:38:30,560 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:38:30,560 : getVerificationCode.py : INFO : 已获取验证码值
2021-07-12 10:39:36,301 : getVerificationCode.py : INFO : 已定位验证码
2021-07-12 10:43:34,251 : getVerificationCode.py : INFO : 获取验证码各顶点坐标
2021-07-12 10:43:34,251 : getVerificationCode.py : INFO : 获取验证码各顶点坐标
2021-07-12 10:44:40,934 : getLog.py : INFO : 1111
2021-07-12 10:44:40,934 : getLog.py : INFO : 2222
2021-07-12 10:44:40,934 : getLog.py : INFO : 3333
2021-07-12 10:45:50,624 : getLog.py : INFO : 1111
2021-07-12 10:45:50,624 : getLog.py : INFO : 2222
2021-07-12 10:45:50,624 : getLog.py : INFO : 3333
2021-07-13 13:44:44,405 : operateExcel.py : ERROR : 文件路径不存在，请检查路径是否正确
2021-07-13 13:44:44,406 : operateExcel.py : ERROR : NoneType: None

2021-07-15 09:17:49,788 : getLog.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/getLog.py", line 82, in func
    num_sum = num1 * num2
TypeError: can't multiply sequence by non-int of type 'str'

2021-07-21 09:26:31,871 : basepage.py : ERROR : 请检查url格式是否正确
2021-07-21 09:26:31,874 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 91, in get
    self.driver.get(url)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:31,877 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:31,877 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:32,381 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:32,381 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:32,889 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:32,889 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:33,403 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:33,404 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:33,909 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:33,910 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:34,418 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:34,418 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:34,925 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:34,926 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:35,434 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:35,435 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:35,944 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:35,945 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:36,453 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:36,454 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:36,971 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:36,973 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:37,487 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:37,487 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:37,995 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:37,995 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:38,508 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:38,509 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:39,016 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:39,016 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:39,528 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:39,529 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:40,039 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:40,040 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:40,547 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:40,548 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:41,055 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:41,055 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:41,564 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:41,565 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:42,073 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:42,073 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:42,580 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:42,581 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:43,087 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:43,087 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:43,592 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:43,593 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:44,102 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:44,103 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:44,613 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:44,614 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:45,117 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:45,117 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:45,631 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:45,632 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:46,145 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:46,146 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:46,652 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:46,652 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:47,158 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:47,159 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:47,668 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:47,669 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:48,180 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:48,181 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:48,689 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:48,689 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:49,196 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:49,196 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:49,705 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:49,705 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:50,213 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:50,214 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:50,726 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:50,727 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:51,241 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:51,242 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:51,754 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:51,755 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 09:26:52,259 : accordingWait.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/accordingWait.py", line 82, in presence_of_element_located
    self._wait.until(
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


2021-07-21 09:26:52,263 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 09:26:52,264 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=91.0.4472.164)


2021-07-21 11:35:23,881 : accordingWait.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/accordingWait.py", line 82, in presence_of_element_located
    self._wait.until(
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 64, in __call__
    return _find_element(driver, self.locator)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 415, in _find_element
    raise e
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=91.0.4472.164)


2021-07-21 11:35:23,895 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 11:35:23,897 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=91.0.4472.164)


2021-07-21 11:36:33,201 : accordingWait.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/Common/accordingWait.py", line 82, in presence_of_element_located
    self._wait.until(
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 71, in until
    value = method(self._driver)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 64, in __call__
    return _find_element(driver, self.locator)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/liushiwen/miniforge3/envs/py38/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/Users/liushiwen/miniforge3/envs/py38/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/Users/liushiwen/miniforge3/envs/py38/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/liushiwen/miniforge3/envs/py38/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt

2021-07-21 11:36:33,202 : basepage.py : ERROR : 请检查定位方式和定位表达式格式是否正确
2021-07-21 11:36:33,203 : basepage.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/liushiwen/miniforge3/envs/py38/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/liushiwen/miniforge3/envs/py38/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/liushiwen/miniforge3/envs/py38/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/liushiwen/miniforge3/envs/py38/lib/python3.8/http/client.py", line 1007, in _send_output
    self.send(msg)
  File "/Users/liushiwen/miniforge3/envs/py38/lib/python3.8/http/client.py", line 947, in send
    self.connect()
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1211173a0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 124, in find_element
    return self.driver.find_element(self.locationTypeDict[location_type.lower()], locator_expression)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=60743): Max retries exceeded with url: /session/f7c340267f9db153b52513943a5e7fd1/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1211173a0>: Failed to establish a new connection: [Errno 61] Connection refused'))

2021-07-21 14:15:20,237 : testUserLogin.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/TestCases/UITestCases/testUserLogin.py", line 26, in test_login
    assert alert_text == "用户名不正确。"
AssertionError: assert '验证码不正确' == '用户名不正确。'
  - 用户名不正确。
  + 验证码不正确

2021-07-21 14:15:20,237 : testUserLogin.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/TestCases/UITestCases/testUserLogin.py", line 26, in test_login
    assert alert_text == "用户名不正确。"
AssertionError: assert '验证码不正确' == '用户名不正确。'
  - 用户名不正确。
  + 验证码不正确

2021-07-21 14:15:33,320 : testUserLogin.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/TestCases/UITestCases/testUserLogin.py", line 25, in test_login
    alert_text = self.login.get_alert_text()
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 512, in get_alert_text
    return self.driver.switch_to.alert.text
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/switch_to.py", line 55, in alert
    alert.text
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/common/alert.py", line 67, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoAlertPresentException: Message: no such alert
  (Session info: chrome=91.0.4472.164)


2021-07-21 14:15:33,320 : testUserLogin.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/TestCases/UITestCases/testUserLogin.py", line 25, in test_login
    alert_text = self.login.get_alert_text()
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 512, in get_alert_text
    return self.driver.switch_to.alert.text
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/switch_to.py", line 55, in alert
    alert.text
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/common/alert.py", line 67, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoAlertPresentException: Message: no such alert
  (Session info: chrome=91.0.4472.164)


2021-07-21 14:16:54,235 : testUserLogin.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/TestCases/UITestCases/testUserLogin.py", line 24, in test_login
    alert_text = self.login.get_alert_text()
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 512, in get_alert_text
    return self.driver.switch_to.alert.text
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/switch_to.py", line 55, in alert
    alert.text
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/common/alert.py", line 67, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoAlertPresentException: Message: no such alert
  (Session info: chrome=91.0.4472.164)


2021-07-21 14:17:47,846 : testUserLogin.py : ERROR : 未捕获到alert事件
2021-07-21 14:17:47,850 : testUserLogin.py : ERROR : Traceback (most recent call last):
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/TestCases/UITestCases/testUserLogin.py", line 24, in test_login
    alert_text = self.login.get_alert_text()
  File "/Users/liushiwen/PycharmProjects/MyTestFramwoek/UITestObjects/BaseFactory/basepage.py", line 512, in get_alert_text
    return self.driver.switch_to.alert.text
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/switch_to.py", line 55, in alert
    alert.text
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/common/alert.py", line 67, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/liushiwen/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoAlertPresentException: Message: no such alert
  (Session info: chrome=91.0.4472.164)


